(print, (eq, (ff, '((a . b) . c)), 'a))
(print, (eq, (equal, 'x, 'x), t))
(print, (eq, (equal, 'x, 'y), nil))
(print, (eq, (equal, '((x, y), x), '((x, y), x)), t))
(print, (eq, (equal, '((x, y), x), '((x, y), y)), nil))
(print, (eq, (null, nil), t))
(print, (eq, (null, 'x), nil))
(print, (eq, (among, 'x, '(y, z, x)), t))
(print, (eq, (among, 'x, '(y, z)), nil))
(print, (eq, (assoc, 'x, '((a, b), (c, d), (x, y))), 'y))
(print, (eq, (assoc, 'z, '((a, b), (c, d), (x, y))), 'notfound))
(print, (equal, (append, '(x, y, z), '(x)), '(x, y, z, x)))
(print, (equal, (pair, '(x, y, z), '(x, y, z)), '((x, x), (y, y), (z, z))))
(print, (equal, (subst, 'x, 'y, '(x, y, z)), '(x, x, z)))
(print, (equal, (sublis, '((x, (a, b)), (y, (b, c))), '(a, x . y)),
                '(a, (a, b), b, c)))
